services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - '8000:8000'

volumes:
  postgres_data:
