# Generated by Django 5.1.7 on 2025-04-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfluencelink',
            name='influence',
        ),
        migrations.AlterUniqueTogether(
            name='artistlistening',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='artistlistening',
            name='listener',
        ),
        migrations.RemoveField(
            model_name='artistlistening',
            name='listening_to',
        ),
        migrations.RemoveField(
            model_name='artistlisteninglink',
            name='listening',
        ),
        migrations.CreateModel(
            name='ArtistConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('influenced_by', 'Influenced By'), ('influences', 'Influences'), ('listens_to', 'Listens To'), ('listened_by', 'Listened By')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='core.artist')),
                ('to_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='core.artist')),
            ],
            options={
                'unique_together': {('from_artist', 'to_artist', 'connection_type')},
            },
        ),
        migrations.CreateModel(
            name='ArtistConnectionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, help_text="Optional note about this source (e.g. 'Rolling Stone 2020 interview')", max_length=255)),
                ('source_type', models.CharField(choices=[('article', 'Article'), ('interview', 'Interview'), ('podcast', 'Podcast'), ('video', 'Video'), ('book', 'Book'), ('social', 'Social Media'), ('other', 'Other')], default='article', help_text='Type of source for this connection', max_length=20)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.artistconnection')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtistInfluence',
        ),
        migrations.DeleteModel(
            name='ArtistInfluenceLink',
        ),
        migrations.DeleteModel(
            name='ArtistListening',
        ),
        migrations.DeleteModel(
            name='ArtistListeningLink',
        ),
    ]
