# Generated by Django 5.1.7 on 2025-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
