# Generated by Django 5.1.7 on 2025-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artistalias_artistmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
