# Generated by Django 5.1.7 on 2025-03-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artist_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
